// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq7wIpPD_iPRFL6VAGNDqjVZcqVz0hCfs',
    appId: '1:933132020080:web:12d08cacbb5e92d07d47b5',
    messagingSenderId: '933132020080',
    projectId: 'evently-e4f54',
    authDomain: 'evently-e4f54.firebaseapp.com',
    storageBucket: 'evently-e4f54.firebasestorage.app',
    measurementId: 'G-S7VEVNXG95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdlvsFRBW4MP8mC-aELC0z5Bi0V5eUYF8',
    appId: '1:933132020080:android:a29147ce12eb86b17d47b5',
    messagingSenderId: '933132020080',
    projectId: 'evently-e4f54',
    storageBucket: 'evently-e4f54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi6VDZebB0Vab0nKiyadtGRrFmRrDLFG0',
    appId: '1:933132020080:ios:50afeb29b372b72d7d47b5',
    messagingSenderId: '933132020080',
    projectId: 'evently-e4f54',
    storageBucket: 'evently-e4f54.firebasestorage.app',
    androidClientId: '933132020080-114eirrmj8n8c72q843bv537hbo7si1u.apps.googleusercontent.com',
    iosClientId: '933132020080-h9ejq1mb7ll724l53mkpf7marfoej5im.apps.googleusercontent.com',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi6VDZebB0Vab0nKiyadtGRrFmRrDLFG0',
    appId: '1:933132020080:ios:50afeb29b372b72d7d47b5',
    messagingSenderId: '933132020080',
    projectId: 'evently-e4f54',
    storageBucket: 'evently-e4f54.firebasestorage.app',
    androidClientId: '933132020080-114eirrmj8n8c72q843bv537hbo7si1u.apps.googleusercontent.com',
    iosClientId: '933132020080-h9ejq1mb7ll724l53mkpf7marfoej5im.apps.googleusercontent.com',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq7wIpPD_iPRFL6VAGNDqjVZcqVz0hCfs',
    appId: '1:933132020080:web:e86070edc01d45797d47b5',
    messagingSenderId: '933132020080',
    projectId: 'evently-e4f54',
    authDomain: 'evently-e4f54.firebaseapp.com',
    storageBucket: 'evently-e4f54.firebasestorage.app',
    measurementId: 'G-9T1KTPL1GE',
  );

}